apiVersion: v1
kind: Secret
metadata:
  name: web-app-secrets
  namespace: web-prod
type: Opaque
stringData:
  DB_USERNAME: "webapp_user"
  DB_PASSWORD: "S3cur3P@ssw0rd!"
  JWT_SECRET: "your-256-bit-jwt-secret-here"
